#!/bin/bash -e

START_POINT=$(pwd)
cd $START_POINT
FS=$START_POINT/core_fs

VER=$(date +%Y%m%d)

KERNEL=$START_POINT/kernel_base/mfs-kernel
mkdir -p mnt

sh zend_encode
cp -av service_enc/* $START_POINT/core_fs/service/

cp -va $FS/* mnt/
echo "$VER" > mnt/etc/firmware
rm -rf mnt/usr/share/{nmap,zoneinfo,smb} mnt/usr/ips_rules
sync
mksquashfs mnt boot.img -all-root -noappend -nopad
sync
IMGZ=$(du -kc boot.img |grep total |tr -s '\t' ':' |cut -d ':' -f 1)
echo "boot.img SIZE=$IMGZ"

mv -v boot.img build/mfs.img
cp -v $KERNEL build/kernel
rm -rf mnt
cd build
rm -fv mfs-*.tgz
tar -zcvf mfs-$VER.tgz kernel mfs.img
echo "mfs-$VER.tgz" > latest-firmware
cd $START_POINT

