#!/bin/sh
HOME_DIR=.
PATH=/usr/local/openssl/bin:$PATH
export PATH
#openssl req -batch -new -x509 -keyout $HOME_DIR/cert/cert.pem > /tmp/cert.csr
#openssl rsa -in /tmp/privkey.pem -out $HOME_DIR/cert/key.pem
#openssl x509 -in /tmp/cert.csr -out $HOME_DIR/cert/cert.pem -req -signkey $HOME_DIR/cert/key.pem -days 1460
#rm -f /tmp/cert.csr /tmp/privkey.pem

openssl req -batch -new -x509 -days 365 -nodes -out $HOME_DIR/cert/key.pem -keyout $HOME_DIR/cert/key.pem
openssl x509 -subject -dates -fingerprint -out $HOME_DIR/cert/cert.pem -in $HOME_DIR/cert/key.pem

chmod 600 $HOME_DIR/cert/key.pem
chmod 600 $HOME_DIR/cert/cert.pem

