#!/bin/bash -e
trap "exit 1" 2;
# checking
if [ "x$_START" = "x" ]; then
        echo "_START not set";
        exit 1;
fi
if [ ! -f "$_START/MYBOX_VERSION" ]; then
        echo "MYBOX_VERSION not set";
        exit 1;
fi
if [ "x$_MK" = "x" ]; then
        echo "_MK not set";
        exit 1;
fi
if [ "x$_MSRC" = "x" ]; then
        echo "_MSRC not set";
        exit 1;
fi
if [ ! -f "$_FUNC/functions.sh" ]; then
        echo "_FUNC not set";
        exit 1;
fi

cd $_START;

. $_FUNC/functions.sh

_BUILD_MSG "image";

_FS="$_START/rootfs";
_KERNEL="$_START/kernel_pkg/mybox-kernel.bin";
_BDIR="/tmp/image";
_IREL="$_START/mybox-boot.bin";
_RELDIR="$_START/OS";


. $_START/MYBOX_VERSION

[ -z "$_VER" ] && _ERROR "_VER not set";
[ -z "$_FIRM" ] && _ERROR "_FIRM not set";
[ ! -e "$_KERNEL" ] && _ERROR "$_KERNEL not found";

rm -rfv $_BDIR;
if ! mkdir -p $_BDIR >/dev/null 2>&1; then
	echo "mkdir $_BDIR failed";
	exit 1;
fi

rm -rf $_RELDIR;
mkdir -p $_RELDIR;

cp -vfa $_FS/* $_BDIR/
echo "$_FIRM" > $_BDIR/etc/firmware
echo "$_VER" > $_BDIR/etc/version_core
sync
[ -f "$_IREL" ] && rm -f $_IREL;
mksquashfs $_BDIR $_IREL -all-root -noappend -nopad
sync
IMGZ=$(du -kc $_IREL |grep total |tr -s '\t' ':' |cut -d ':' -f 1)
echo "$_IREL SIZE=$IMGZ"
_MECHO "rm -rf $_BDIR";
_MECHO "mv -v $_IREL $_RELDIR";
_MECHO "cp -v $_KERNEL $_RELDIR";
_MECHO "cd $_START";
exit 0;
