#!/bin/bash
ROOT_DIR=$(pwd)
SRC_DIR=$ROOT_DIR/service
TMP_DIR=$ROOT_DIR/service_tmp
DST_DIR=$ROOT_DIR/service_enc

cd $ROOT_DIR
rm -rfv $DST_DIR
rm -rfv $TMP_DIR
if [ ! -d "$DST_DIR" ]; then
	mkdir -p $DST_DIR
fi

find $SRC_DIR/* -name '*.ex*' |xargs dos2unix
find $SRC_DIR/* -name '*.init' |xargs dos2unix
find $SRC_DIR/* -name '*.js' |xargs dos2unix
find $SRC_DIR/* -name '*.css' |xargs dos2unix

cp -av $SRC_DIR $TMP_DIR
find $TMP_DIR/* -name '*.ex*' > /tmp/f.list
find $TMP_DIR/* -name '*.init' >> /tmp/f.list

for f in $(cat /tmp/f.list);do
	read h < $f
	[ "$h" != "<?" ] && echo "$h" > $f.tmp
	php -w $f | php -f html_strip > $f.tmp1
	#php -n -q $ROOT_DIR/www_encode "$f.tmp1" >> $f.tmp
	cat $f.tmp1 >> $f.tmp
	rm -f $f.tmp1
	cat $f.tmp > $f
	rm -f $f.tmp && chmod 700 $f
done

rm -f /tmp/f.list

# --encoded-only \

/usr/local/Zend/bin/zendenc \
--quiet  \
--recursive \
--short-tags on \
--ignore-errors \
--asp-tags off \
--optimizations 1023 \
--no-default-extensions \
--include-ext exh \
--include-ext exl \
--include-ext inc \
--include-ext php \
--include-ext exc \
--include-ext jse \
--include-ext lang \
--include-ext init \
--no-header \
--ignore "CVS" \
--ignore ".cvsignore"  \
--ignore ".backup"  \
--ignore "Thumbs.db"  \
$TMP_DIR \
$DST_DIR

cd $ROOT_DIR
rm -rfv $TMP_DIR

#sh license_encode

