#!/bin/bash -e

START_POINT=$(pwd)
cd $START_POINT
FS=$START_POINT/rootfs
VER=$(date +%Y%m%d)
REL="v2.1"

KERNEL=$START_POINT/kernel_base/mfs-kernel
rm -rfv mnt
mkdir -p mnt

cp -va $FS/* mnt/
rm -rf mnt/usr/share/nmap mnt/usr/ips_rules
echo "$VER" > mnt/etc/firmware
sync
mksquashfs mnt boot.img -all-root -noappend -nopad
sync
IMGZ=$(du -kc boot.img |grep total |tr -s '\t' ':' |cut -d ':' -f 1)
echo "boot.img SIZE=$IMGZ"
mv -v boot.img build/myboxsys.bin
cp -v $KERNEL build/myboxos.bin
rm -rf mnt
cd build
rm -fv myboxOS.*
tar -zcvf myboxOS.$REL.$VER.bin myboxos.bin myboxsys.bin
echo "myboxOS.$REL.$VER" > latest-firmware
cd $START_POINT

