#!/bin/sh
# $Id: exec_ssh.sh,v 1.0 2008/01/24 12:39:00 nawawi Exp $
# iosh ssh helper

export PATH="/bin";

_HOST="$1";
_USER="$2";
_PORT="$3";

if [ "x$_HOST" = "x" -a "x$_USER" = "x" ]; then
        echo "% Invalid options";
        exit 1;
fi
[ "x$_PORT" != "x" ] && _PORT="-p $_PORT";
/bin/ssh $USER@$HOST $PORT;
exit $?;


