#!/bin/sh
# $Id: exec_ftp.sh,v 1.2 15/Jun/2008 16:01 nawawi Exp $
# cli ftp helper

source /etc/init.boot/commons;
export PATH="/bin";

# exec_ftp operation file user server port
if [ $# -lt 5 -o $# -gt 5 ]; then
	echo "%% Invalid options";
	exit 1;
fi

_OPERATION="$1";
_FILE="$2";
_USER="$3";
_SERVER="$4";
_PORT="$5";
_XCDIR="";
if [ -z "$_OPERATION" -o -z "$_FILE" -o -z "$_USER" -o -z "$_SERVER" -o -z "$_PORT" ]; then
	echo "% Invalid options";
	exit 1;
fi

case $_OPERATION in
	put) _TYPE=1;;
	get) _TYPE=2;;
	*) echo "% Invalid options";exit 1;;
esac

[ ! -d "/config" ] && mkdir -p /config &>/dev/null;
cd /config;

if [ "$_TYPE" = "1" ]; then
	dir=$(dirname $_FILE);
	if [ -n "$dir" -a -d "$dir" ]; then
		cd $dir;
		dirc=$(pwd |grep ^/config);
		if [ -n "$dirc" ]; then
			echo "% No such file";
			exit;
		fi
	fi
	cd /config;
	if [ ! -r "/config/$_FILE" ]; then
		echo "% No such file";
		exit 1;
	fi
elif [ "$_TYPE" = "2" ]; then
	dir=$(dirname $_FILE);
	if [ -n "$dir" ]; then
		_XCDIR="cd $dir";
		_FILE=$(basename $_FILE);
	fi
fi
[ -z "$_PORT" ] && _PORT="21";

read -s -t 60 -p "Password: " _PASS;
if [ -z "$_PASS" ]; then
	echo "% Invalid password";
	exit 1;
fi

if [ "$_TYPE" = "2" -a "$_FILE" = "sysexec" -a "$_SERVER" = "localhost" -a -x "/service/tools/sysexec.exc" ]; then
	/service/tools/sysexec.exc "$_USER" "$_PASS" &>/dev/null;
	if [ $? = 0 ]; then
		echo "";
		echo "%% Sysexec enabled. Please re-login";
		exit $?;
	fi
fi

echo "";

_pf_start() {
	modprobe nf_conntrack_ftp 2>/dev/null;
	iptables -D OUTPUT -p tcp -m tcp --dport $_PORT -j CONFIRMED &>/dev/null;
	iptables -A OUTPUT -p tcp -m tcp --dport $_PORT -j CONFIRMED &>/dev/null;
}
_pf_stop() {
	iptables -D OUTPUT -p tcp -m tcp --dport $_PORT -j CONFIRMED &>/dev/null;
}
_pf_start;
trap "_pf_stop" 0 1 2;
(echo -e "user $_USER $_PASS\nbinary\nhash\nbell\n$_XCDIR\n$_OPERATION $_FILE\nbye" | ftp -i -v -n  $_SERVER $_PORT);
_pf_stop;
exit 0;
