#!/bin/sh
# $Id: exec_reboot.sh,v 1.0 2008/01/24 12:39:00 nawawi Exp $
# iosh reboot helper

trap : 1 2 3 15
export PATH="/bin";
source /etc/init.boot/commons;

_OPTION="$1";
if [ -n "$_OPTION" ]; then
	case $_OPTION in
		reboot) reboot;;
		shutdown) shutdown;;
	esac
fi
exit 0;

