#!/bin/sh

[ ! -d /sys/ ] && exit 1;

: >/tmp/modules-plain
: >/tmp/modules-stripped
: >/tmp/modules-sorted
: >/tmp/moduleslist

# find pci aliases
aliases=$(find /sys/ -noleaf -name modalias  -exec cat {} +);

# check for empty aliases
if [ "$aliases" == "" ]; then
	exit 1
fi

# generate files for the different actions
modprobe -a --show-depends $aliases >> /tmp/modules-plain 2>/dev/null

# fix ide cdrom detection on proliant 1600
if [ "$(echo $aliases | grep 'pci:v00000E11d00000001sv00000000sd00000000bc06sc02i00')" ]; then
	modprobe -i --show-depends ide-generic >> /tmp/modules-plain 2>/dev/null
fi

# find PNP devices like parports, soundcards etc.
#   (workaround for rtc, pcspkr, irtty-sir and analog are included)
if [ "$(find /sys/devices -noleaf -name 'id' | grep /pnp)" ]; then
	for i in $(find /sys/devices -noleaf -name "id" | grep /pnp); do
		devid=$(cat $i | grep PNP);
		[ "$devid" ] || continue
	
		modprobe -i --show-depends pnp:d${devid} >> /tmp/modules-plain 2>/dev/null
	
		[ "$devid" == "PNP0800" ] && modprobe -i --show-depends pcspkr 2>/dev/null >> /tmp/modules-plain  2>/dev/null
		[ "$devid" == "PNP0b00" ] && modprobe -i --show-depends rtc_proc 2>/dev/null >> /tmp/modules-plain  2>/dev/null
		[ "$devid" == "PNP0b00" ] && modprobe -i --show-depends rtc_sysfs 2>/dev/null >> /tmp/modules-plain
		[ "$devid" == "PNP0b00" ] && modprobe -i --show-depends rtc_dev 2>/dev/null >> /tmp/modules-plain
		[ "$devid" == "PNP0510" ] && modprobe -i --show-depends irtty-sir 2>/dev/null >> /tmp/modules-plain 2>/dev/null
		[ "$devid" == "PNP0511" ] && modprobe -i --show-depends irtty-sir 2>/dev/null >> /tmp/modules-plain 2>/dev/null
		[ "$devid" == "PNPb02f" ] && modprobe -i --show-depends analog 2>/dev/null >> /tmp/modules-plain 2>/dev/null

		# load ppp-generic if serial ports are detected for modems
		[ "$devid" == "PNP0501" ] && modprobe -i --show-depends ppp-generic 2>/dev/null >> /tmp/modules-plain 2>/dev/null
	done
fi

# SCSI disks/cdroms/tapes/generic devices
if [ "$(find /sys/devices -noleaf -name 'type')" ]; then
	for i in $(cat $(find /sys/devices -noleaf -name "type")); do
		case $i in (4|5)	modprobe -i --show-depends sr-mod >> /tmp/modules-plain 2>/dev/null ;; esac
		case $i in (2|3|6|8|9)	modprobe -i --show-depends sg >> /tmp/modules-plain 2>/dev/null ;; esac
		case $i in (0|7|14)	modprobe -i --show-depends sd-mod >> /tmp/modules-plain 2>/dev/null ;; esac
		case $i in (1)           modprobe -i --show-depends st >> /tmp/modules-plain 2>/dev/null ;; esac
	done
fi

# add Buslogic for vmware
if [ "$VMWARE" = "1" ]; then
	 modprobe -i --show-depends BusLogic >> /tmp/modules-plain 2>/dev/null
fi

# Parport modules
if [ "$(grep 'parport' /tmp/modules-plain)" ]; then
	modprobe -i --show-depends lp >> /tmp/modules-plain 2>/dev/null
	modprobe -i --show-depends ppdev >> /tmp/modules-plain 2>/dev/null
fi

# Sound OSS compat modules
if [ "$(grep 'snd-pcm' /tmp/modules-plain)" ]; then
	modprobe -i --show-depends snd-pcm-oss >> /tmp/modules-plain 2>/dev/null
fi
if [ "$(grep 'snd-seq' /tmp/modules-plain)" ]; then
	modprobe -i --show-depends snd-seq-oss >> /tmp/modules-plain 2>/dev/null
fi

sort -u /tmp/modules-plain >> /tmp/modules-stripped

# OTHER modules loading first for speed up!
grep -v "ide/" /tmp/modules-stripped | \
grep -v "scsi/" | \
grep -v "fusion/" | \
grep -v "block/sx8" | \
grep -v "message/fusion" | \
grep -v  "block/cciss" | \
grep -v "block/cpqarray" | \
grep -v "block/DAC960" | grep -v "ata/" | \
grep -v "net/" | \
grep -v "pcmcia/" | \
grep -v "usb/" | \
grep -v "ieee1394/" >> /tmp/modules-sorted

# make a correct order for the modules, internal devices have priority!
# only use old ide modules if boot parameter 'ide-legacy' is given
if [ "$IDE_LEGACY" = "1" ]; then
		grep "ide/" /tmp/modules-stripped >> /tmp/modules-sorted
else
	grep "ata/pata" /tmp/modules-stripped >> /tmp/modules-sorted
	grep "ata/ata_generic" /tmp/modules-stripped >> /tmp/modules-sorted
fi
grep "scsi/" /tmp/modules-stripped | grep -v "sd_mod" | grep -v "sr_mod" | grep -v "/sg.ko" | grep -v "/st.ko" >> /tmp/modules-sorted
grep "block/" /tmp/modules-stripped | grep -v "sx8" | grep -v "nbd" | grep -v "pktcdvd" | grep -v "floppy" >> /tmp/modules-sorted
grep "fusion/" /tmp/modules-stripped >> /tmp/modules-sorted
grep "ata/"  /tmp/modules-stripped| grep -v "pata" | grep -v "ata_generic" | grep -v "libata" >> /tmp/modules-sorted
grep "block/" /tmp/modules-stripped | grep "sx8" >> /tmp/modules-sorted
grep "net/" /tmp/modules-stripped | grep -v "wireless/" | grep -v "usb/" >> /tmp/modules-sorted
grep "wireless/" /tmp/modules-stripped >> /tmp/modules-sorted
grep "pcmcia/" /tmp/modules-stripped >> /tmp/modules-sorted

# speed up usb module loading
grep "usb-storage" /tmp/modules-stripped >> /tmp/modules-sorted
grep "usblp" /tmp/modules-stripped >> /tmp/modules-sorted
grep "usbhid" /tmp/modules-stripped >> /tmp/modules-sorted
grep "usb/" /tmp/modules-stripped | grep -v "usb-storage" | grep -v "usbhid" | grep -v "usblp" >> /tmp/modules-sorted
grep "firewire/" /tmp/modules-stripped >> /tmp/modules-sorted
grep "ieee1394/" /tmp/modules-stripped >> /tmp/modules-sorted

# add scsi device modules at the end
grep "sd_mod" /tmp/modules-stripped >> /tmp/modules-sorted
grep "sr_mod" /tmp/modules-stripped >> /tmp/modules-sorted
grep "/st.ko" /tmp/modules-stripped >> /tmp/modules-sorted
grep "/sg.ko" /tmp/modules-stripped >> /tmp/modules-sorted
sed -ne "s#^insmod.*/\(.*\)\.ko.*#\1#p" /tmp/modules-sorted >> /tmp/moduleslist
exit 0;

