# Copyright (c) 2004 Alexander Eremin <xyzyx@rambler.ru>

all: ripd

include MCONFIG
include MRULES

OBJS=	af.o if.o input.o ripd.o output.o startup.o \
	tables.o timer.o trace.o inet.o

ripd: $(OBJS)
	

