#!/bin/sh
# $Id: wall,v 1.1 2008/03/10 23:50:56 nawawi Exp $
# Copyright (c) 2008 Tracenetwork Corporation Sdn. Bhd.
# send msg to all device

_ME="$(tty)";

msg() {
	local txt="$@";
	local _mtxt=$"Message from %s";
	if [ -n "$txt" ]; then
		[ -w "/dev/ttyS0" ] && echo -e "$(printf "$_mtxt" "$_ME"):\n\n$txt\n\n" >> /dev/ttyS0 2>/dev/null;
		[ -w "/dev/tty1" ] && echo -e "$(printf "$_mtxt" "$_ME"):\n\n$txt\n\n" >> /dev/tty1 2>/dev/null;
		if [ -d "/dev/pts" ]; then
			for f in /dev/pts/*;do
				[ -w "$f" ] && echo -e "$(printf "$_mtxt" "$_ME"):\n\n$txt\n\n" >> $f 2>/dev/null;
			done
		fi
	fi
}

msg $@;
exit 0;
