#!/bin/sh
# $Id: exec_reboot.sh,v 1.0 2008/01/24 12:39:00 nawawi Exp $
# iosh reboot helper

trap : 1 2 3 15
PATH="/bin"
. /etc/init.boot/functions

OPT=$1
if [ "x$OPT" != "x" ]; then
	case $OPT in
		reboot) reboot;;
		shutdown) shutdown;;
	esac
fi
exit $?

